# Version: 1.0
# Date: 2025-06-05
blueprint:
  name: Z2M - SONOFF SNZB-01 Wireless Button v1.0
  description: |
    Automation blueprint for SONOFF SNZB-01 wireless switches connected through Zigbee2MQTT.
    Handles all button actions:
    - Single press
    - Double press
    - Long press

    Select your SONOFF SNZB-01 device from the dropdown and configure the actions you want to trigger for each button press type.
  domain: automation
  input:
    button_device:
      name: Remote
      description: Select your SONOFF SNZB-01 device
      selector:
        device:
          integration: mqtt
          manufacturer: SONOFF
          model: "Wireless button"
    single_press:
      name: Single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double press
      default: []
      selector:
        action: {}
    long_press:
      name: Long press
      default: []
      selector:
        action: {}

trigger:
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    id: "single"
    subtype: single
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    id: "double"
    subtype: double
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    id: "long"
    subtype: long

variables:
  action: "{{ trigger.id }}"

action:
  - choose:
      - conditions: "{{ action == 'single' }}"
        sequence: !input single_press
      - conditions: "{{ action == 'double' }}"
        sequence: !input double_press
      - conditions: "{{ action in ['long', 'release'] }}"
        sequence: !input long_press
mode: queued
