# Version: 1.8
# Date: 2025-06-05
blueprint:
  name: Z2M - eWeLink ZB-SW03 3 Gang Switch v1.8
  description: |
    Automation blueprint for eWeLink ZB-SW03 3-gang Zigbee switches connected through Zigbee2MQTT.
    Each button (Left, Center, Right) can trigger a different action depending on its state (on/off/unknown).
    Select the switch entities from your eWeLink ZB-SW03 device and configure the actions for each state.
  domain: automation
  input:
    left_switch:
      name: Left Switch
      description: Select the left switch entity
      selector:
        entity:
          domain: switch
          multiple: false
    left_button_on:
      name: Left Switch - Action if ON
      default: []
      selector:
        action: {}
    left_button_off:
      name: Left Switch - Action if OFF
      default: []
      selector:
        action: {}
    left_button_fallback:
      name: Left Switch - Fallback Action
      default: []
      selector:
        action: {}

    center_switch:
      name: Center Switch
      description: Select the center switch entity
      selector:
        entity:
          domain: switch
          multiple: false
    center_button_on:
      name: Center Switch - Action if ON
      default: []
      selector:
        action: {}
    center_button_off:
      name: Center Switch - Action if OFF
      default: []
      selector:
        action: {}
    center_button_fallback:
      name: Center Switch - Fallback Action
      default: []
      selector:
        action: {}

    right_switch:
      name: Right Switch
      description: Select the right switch entity
      selector:
        entity:
          domain: switch
          multiple: false
    right_button_on:
      name: Right Switch - Action if ON
      default: []
      selector:
        action: {}
    right_button_off:
      name: Right Switch - Action if OFF
      default: []
      selector:
        action: {}
    right_button_fallback:
      name: Right Switch - Fallback Action
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input left_switch
    id: left_button
  - platform: state
    entity_id: !input center_switch
    id: center_button
  - platform: state
    entity_id: !input right_switch
    id: right_button

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: left_button
          - condition: state
            entity_id: !input left_switch
            state: "on"
        sequence: !input left_button_on
      - conditions:
          - condition: trigger
            id: left_button
          - condition: state
            entity_id: !input left_switch
            state: "off"
        sequence: !input left_button_off
      - conditions:
          - condition: trigger
            id: center_button
          - condition: state
            entity_id: !input center_switch
            state: "on"
        sequence: !input center_button_on
      - conditions:
          - condition: trigger
            id: center_button
          - condition: state
            entity_id: !input center_switch
            state: "off"
        sequence: !input center_button_off
      - conditions:
          - condition: trigger
            id: right_button
          - condition: state
            entity_id: !input right_switch
            state: "on"
        sequence: !input right_button_on
      - conditions:
          - condition: trigger
            id: right_button
          - condition: state
            entity_id: !input right_switch
            state: "off"
        sequence: !input right_button_off
    default: []
