# Version: 1.6
# Date: 2025-06-05
blueprint:
  name: Z2M - eWeLink ZB-SW03 3 Gang Switch v1.6
  description: |
    Automation blueprint for eWeLink ZB-SW03 3-gang Zigbee switches connected through Zigbee2MQTT.
    Each button (Left, Center, Right) can trigger a different action depending on its state (on/off/unknown).
    Select your switch device once, and then choose the specific switch entities for each button.
  domain: automation
  input:
    switch_device:
      name: Switch Device
      description: Select your eWeLink ZB-SW03 3-gang switch
      selector:
        device:
          integration: mqtt
          manufacturer: eWeLink
          model: "Smart light switch - 3 gang"
    left_button_on:
      name: Left Button - Action if ON
      default: []
      selector:
        action: {}
    left_button_off:
      name: Left Button - Action if OFF
      default: []
      selector:
        action: {}
    left_button_fallback:
      name: Left Button - Fallback Action
      default: []
      selector:
        action: {}

    center_button_on:
      name: Center Button - Action if ON
      default: []
      selector:
        action: {}
    center_button_off:
      name: Center Button - Action if OFF
      default: []
      selector:
        action: {}
    center_button_fallback:
      name: Center Button - Fallback Action
      default: []
      selector:
        action: {}

    right_button_on:
      name: Right Button - Action if ON
      default: []
      selector:
        action: {}
    right_button_off:
      name: Right Button - Action if OFF
      default: []
      selector:
        action: {}
    right_button_fallback:
      name: Right Button - Fallback Action
      default: []
      selector:
        action: {}

trigger:
  - platform: device
    domain: mqtt
    device_id: !input switch_device
    type: state
    subtype: left_switch
    id: left_button
  - platform: device
    domain: mqtt
    device_id: !input switch_device
    type: state
    subtype: center_switch
    id: center_button
  - platform: device
    domain: mqtt
    device_id: !input switch_device
    type: state
    subtype: right_switch
    id: right_button

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: left_button
          - condition: device
            device_id: !input switch_device
            domain: mqtt
            type: is_on
            subtype: left_switch
        sequence: !input left_button_on
      - conditions:
          - condition: trigger
            id: left_button
          - condition: device
            device_id: !input switch_device
            domain: mqtt
            type: is_off
            subtype: left_switch
        sequence: !input left_button_off
      - conditions:
          - condition: trigger
            id: center_button
          - condition: device
            device_id: !input switch_device
            domain: mqtt
            type: is_on
            subtype: center_switch
        sequence: !input center_button_on
      - conditions:
          - condition: trigger
            id: center_button
          - condition: device
            device_id: !input switch_device
            domain: mqtt
            type: is_off
            subtype: center_switch
        sequence: !input center_button_off
      - conditions:
          - condition: trigger
            id: right_button
          - condition: device
            device_id: !input switch_device
            domain: mqtt
            type: is_on
            subtype: right_switch
        sequence: !input right_button_on
      - conditions:
          - condition: trigger
            id: right_button
          - condition: device
            device_id: !input switch_device
            domain: mqtt
            type: is_off
            subtype: right_switch
        sequence: !input right_button_off
    default: !input button_fallback
