# Version: 1.1
# Date: 2025-06-05
blueprint:
  source_url: https://raw.githubusercontent.com/pabloflego/home-assistant/refs/heads/main/blueprints/button/z2m_tuya_st004f_4gang.yaml
  name: Z2M - Tuya 4-Button Scene Switch TS004F v1.1
  description: >-
    Automate your Tuya 4-Button Scene Switch (TS004F) via Zigbee2MQTT.
    Supports single press, double press, and hold actions for all 4 buttons.
    Make sure the device is in "event" mode by holding buttons 2+4 for 6 seconds until light 3 flashes once.
    Link - https://www.zigbee2mqtt.io/devices/TS004F.html
  domain: automation
  input:
    button_device:
      name: Button Device
      description: Select your Tuya TS004F device
      selector:
        device:
          integration: mqtt
          manufacturer: Tuya
          model: "Wireless switch with 4 buttons"
    button_1_single:
      name: Top Left - Single Press
      description: Action to run on single press of top left button
      default: []
      selector:
        action: {}
    button_1_double:
      name: Top Left - Double Press
      description: Action to run on double press of top left button
      default: []
      selector:
        action: {}
    button_1_hold:
      name: Top Left - Hold
      description: Action to run when top left button is held
      default: []
      selector:
        action: {}
    button_2_single:
      name: Top Right - Single Press
      description: Action to run on single press of top right button
      default: []
      selector:
        action: {}
    button_2_double:
      name: Top Right - Double Press
      description: Action to run on double press of top right button
      default: []
      selector:
        action: {}
    button_2_hold:
      name: Top Right - Hold
      description: Action to run when top right button is held
      default: []
      selector:
        action: {}
    button_3_single:
      name: Bottom Left - Single Press
      description: Action to run on single press of bottom left button
      default: []
      selector:
        action: {}
    button_3_double:
      name: Bottom Left - Double Press
      description: Action to run on double press of bottom left button
      default: []
      selector:
        action: {}
    button_3_hold:
      name: Bottom Left - Hold
      description: Action to run when bottom left button is held
      default: []
      selector:
        action: {}
    button_4_single:
      name: Bottom Right - Single Press
      description: Action to run on single press of bottom right button
      default: []
      selector:
        action: {}
    button_4_double:
      name: Bottom Right - Double Press
      description: Action to run on double press of bottom right button
      default: []
      selector:
        action: {}
    button_4_hold:
      name: Bottom Right - Hold
      description: Action to run when bottom right button is held
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

trigger:
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "1_single"
    id: "1_single"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "1_double"
    id: "1_double"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "1_hold"
    id: "1_hold"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "2_single"
    id: "2_single"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "2_double"
    id: "2_double"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "2_hold"
    id: "2_hold"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "3_single"
    id: "3_single"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "3_double"
    id: "3_double"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "3_hold"
    id: "3_hold"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "4_single"
    id: "4_single"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "4_double"
    id: "4_double"
  - platform: device
    domain: mqtt
    device_id: !input button_device
    type: action
    subtype: "4_hold"
    id: "4_hold"

variables:
  action: "{{ trigger.id }}"

action:
  - choose:
      - conditions: "{{ action == '1_single' }}"
        sequence: !input button_1_single
      - conditions: "{{ action == '1_double' }}"
        sequence: !input button_1_double
      - conditions: "{{ action == '1_hold' }}"
        sequence: !input button_1_hold
      - conditions: "{{ action == '2_single' }}"
        sequence: !input button_2_single
      - conditions: "{{ action == '2_double' }}"
        sequence: !input button_2_double
      - conditions: "{{ action == '2_hold' }}"
        sequence: !input button_2_hold
      - conditions: "{{ action == '3_single' }}"
        sequence: !input button_3_single
      - conditions: "{{ action == '3_double' }}"
        sequence: !input button_3_double
      - conditions: "{{ action == '3_hold' }}"
        sequence: !input button_3_hold
      - conditions: "{{ action == '4_single' }}"
        sequence: !input button_4_single
      - conditions: "{{ action == '4_double' }}"
        sequence: !input button_4_double
      - conditions: "{{ action == '4_hold' }}"
        sequence: !input button_4_hold
