blueprint:
  name: Z2M - Generic Single Button
  description: |
    Handle single, double, and long presses from any Zigbee2MQTT button.
    You must manually enter the MQTT topic. 'release' is treated as 'long'.
  domain: automation
  input:
    button_topic:
      name: MQTT Topic
      description: The Zigbee2MQTT topic of the button (e.g., zigbee2mqtt/bn04_under_desk)
      selector:
        text:
    single_press:
      name: Single press
      default: []
      selector:
        action: {}
    double_press:
      name: Double press
      default: []
      selector:
        action: {}
    long_press:
      name: Long press (includes 'release')
      default: []
      selector:
        action: {}

trigger:
  - platform: mqtt
    topic: !input button_topic

variables:
  action: "{{ trigger.payload_json.action }}"

action:
  - choose:
      - conditions: "{{ action == 'single' }}"
        sequence: !input single_press
      - conditions: "{{ action == 'double' }}"
        sequence: !input double_press
      - conditions: "{{ action in ['long', 'release'] }}"
        sequence: !input long_press
mode: queued
