# Version: 0.1
# Date: 2025-06-05
blueprint:
  name: Z2M - ZB-SW03 3 Button Switch with State-Aware Actions (HA Entities)
  description: |
    Responds to state changes on a 3-gang Zigbee2MQTT switch (like eWeLink ZB-SW03).
    Each button can trigger a different action depending on whether its switch entity is on, off, or in an unknown state.
    Select the Home Assistant switch entities directly for a better user experience.
  domain: automation
  input:
    button_1_entity:
      name: Button 1 Switch Entity
      selector:
        entity:
          domain: switch
    button_1_on:
      name: Button 1 - Action if ON
      default: []
      selector:
        action: {}
    button_1_off:
      name: Button 1 - Action if OFF
      default: []
      selector:
        action: {}
    button_1_fallback:
      name: Button 1 - Fallback Action
      default: []
      selector:
        action: {}

    button_2_entity:
      name: Button 2 Switch Entity
      selector:
        entity:
          domain: switch
    button_2_on:
      name: Button 2 - Action if ON
      default: []
      selector:
        action: {}
    button_2_off:
      name: Button 2 - Action if OFF
      default: []
      selector:
        action: {}
    button_2_fallback:
      name: Button 2 - Fallback Action
      default: []
      selector:
        action: {}

    button_3_entity:
      name: Button 3 Switch Entity
      selector:
        entity:
          domain: switch
    button_3_on:
      name: Button 3 - Action if ON
      default: []
      selector:
        action: {}
    button_3_off:
      name: Button 3 - Action if OFF
      default: []
      selector:
        action: {}
    button_3_fallback:
      name: Button 3 - Fallback Action
      default: []
      selector:
        action: {}

trigger:
  - platform: state
    entity_id: !input button_1_entity
    id: button_1
  - platform: state
    entity_id: !input button_2_entity
    id: button_2
  - platform: state
    entity_id: !input button_3_entity
    id: button_3

condition: []

action:
  - choose:
      - conditions:
          - condition: trigger
            id: button_1
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input button_1_entity
                    state: "on"
                sequence: !input button_1_on
              - conditions:
                  - condition: state
                    entity_id: !input button_1_entity
                    state: "off"
                sequence: !input button_1_off
            default: !input button_1_fallback

      - conditions:
          - condition: trigger
            id: button_2
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input button_2_entity
                    state: "on"
                sequence: !input button_2_on
              - conditions:
                  - condition: state
                    entity_id: !input button_2_entity
                    state: "off"
                sequence: !input button_2_off
            default: !input button_2_fallback

      - conditions:
          - condition: trigger
            id: button_3
        sequence:
          - choose:
              - conditions:
                  - condition: state
                    entity_id: !input button_3_entity
                    state: "on"
                sequence: !input button_3_on
              - conditions:
                  - condition: state
                    entity_id: !input button_3_entity
                    state: "off"
                sequence: !input button_3_off
            default: !input button_3_fallback
